name: Red_Murder
api-version: "1.20"
version: 1.0
authors: [Red_Spash]
main: fr.red_spash.murder.Murder
description: §cMurder §6par §6§l@Red_Spash
commands:
  editWorld:
  spawns:
  saveWorld:
  start:
  teleportTo:

