name: Java Checkstyle Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 11 with Eclipse Temurin distribution
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Install Maven
      - name: Set up Maven
        run: sudo apt-get install maven -y

      # 4. Run Checkstyle via Maven and fail on warnings/errors
      - name: Run Checkstyle
        run: mvn checkstyle:check
